wandb_version: 1

lr:
  desc: null
  value: 1.0e-05
mlp:
  desc: null
  value: 3
return:
  desc: null
  value: Bellman
linear:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683988995.866344
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.7.16
      5: 0.15.2
      8:
      - 5
